name: Christopher Kodama's Website
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-postcss-v2
postcss:
  cache: false
collections:
  projects:
    output: true
    order:
      - pdf_bullets.md