name: Christopher Kodama's Website
markdown: kramdown
plugins:
  - jekyll-postcss-v2
postcss:
  cache: false
collections:
  projects:
    output: true
    order:
      - dialogue_summarizer.md
      - web_product_scraper.md
      - pdf_bullets.md
      - performance_statement_generator.md
      - teachable_text_machine.md
      - resume_build_pipeline.md
      - home_lab.md